# Generated by Django 3.2.16 on 2023-03-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=200, verbose_name='Подписчик')),
                ('folowing', models.TextField(verbose_name='Автор')),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
