# Generated by Django 3.2.16 on 2023-03-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230319_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='name',
            new_name='following',
        ),
    ]
